name: Test


on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: install modules
        run: npm install --force

      - name: Test unitaire
        run: npx jest --ci --reporters=default --reporters=jest-junit


